apiVersion: v1
kind: Pod
metadata:
  name: jdbc-tracing
spec:
  containers:
  - image: jdbc-tracing:latest
    imagePullPolicy: IfNotPresent
    name: app
    resources:
      limits:
        cpu: "1"
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi
